### ISSUE TITLE
No executable in Windows Release

### ISSUE THREAD

**Issue by minecraftchest1** [ajmcateer/GotifyDesktop#11]
In the latest Windows release download, there is no .exe file to start the app with. There is a exe in there, but it doesn't appear to be related to the app.  Renaming the GotifyDesktop file to end with .exe gives an executable, but generates an application to big to fit in memory error.

**Comment by squromiv** [comment]
Same problem

**Comment by minecraftchest1** [comment]
I found that the problem is with the beta build. The alpha build doesn't have the issue.

**Comment by KibosJ** [comment]
The Mac download contains the Windows version and the Windows download contains the Mac version; they've just been uploaded the wrong way round by the looks of it

**Comment by ajmcateer** [comment]
Thanks @KibosJ for helping them. I have been distracted with a new job, but recently started looking into this again. I will upload a new build with this fixed.
