### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by jmattheis** [ajmcateer/GotifyDesktop#2]
Hey there, 

looks good. But I think there is still a lot todo, here some bullet points.

* Logout
* Cleaner login, maybe have an input where the whole url can be inserted. Having different inputs for port is inconvinient
* better sync of messages. Currently if a message gets deleted when the application is not active, then it stays in the database. Instead of saving the messages to a local db the app could just request them every time the application is started.
* Continuous Integration - Automatic Builds and stuff
* Build Instructions in Readme

**Comment by ajmcateer** [comment]
Thanks for the feedback sorry it took so long to respond had to spend some time working on something for work I implemented some of your suggestions and are working on more right now. Let me know if you have any other feedback.
